---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install system dependencies
  apt:
    name: "{{ system_packages }}"
    state: present
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
