---
- name: Allowe Swarm-ports on Managers
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: "{{ 'udp' if item in ['7946', '4789'] else 'tcp' }}"
  loop:
    - 22
    - 2377
    - 7946
    - 4789
  when: "'managers' in group_names"
  tags: firewall

- name: Allow Swarm-ports on Workers
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: "{{ 'udp' if item in ['7946', '4789'] else 'tcp' }}"
  loop:
    - 22
    - 7946
    - 4789
  when: "'workers' in group_names"
  tags: firewall

- name: Check swarm status on all nodes
  shell: "docker info --format '{% raw %}{{.Swarm.LocalNodeState}}{% endraw %}'"
  register: swarm_status
  changed_when: false

- name: Initialize Swarm on first manager
  shell: |
    docker swarm init --advertise-addr {{ hostvars[groups['managers'][0]]['ansible_host'] }}:2377
    docker swarm join-token manager -q > /tmp/swarm_manager_token
    docker swarm join-token worker -q > /tmp/swarm_worker_token
  args:
    chdir: /tmp
  register: init_result
  when: 
    - "'managers' in group_names"
    - inventory_hostname == groups['managers'][0]
    - swarm_status.stdout != "active"
  changed_when: false

- name: Get Manager Token
  shell: cat /tmp/swarm_manager_token
  register: manager_token
  when: 
    - "'managers' in group_names"
    - inventory_hostname == groups['managers'][0]
  delegate_to: "{{ groups['managers'][0] }}"
  run_once: true

- name: Get Worker Token
  shell: cat /tmp/swarm_worker_token
  register: worker_token
  when: 
    - "'managers' in group_names"
    - inventory_hostname == groups['managers'][0]
  delegate_to: "{{ groups['managers'][0] }}"
  run_once: true

- name: Adding Additional Managers
  shell: |
    docker swarm join --token {{ manager_token.stdout }} {{ hostvars[groups['managers'][0]]['ansible_host'] }}:2377
  when: 
    - "'managers' in group_names"
    - inventory_hostname != groups['managers'][0]
    - swarm_status.stdout != "active"

- name: Adding Workers
  shell: |
    docker swarm join --token {{ worker_token.stdout }} {{ hostvars[groups['managers'][0]]['ansible_host'] }}:2377
  when: 
    - "'workers' in group_names"
    - swarm_status.stdout != "active"